markdown: kramdown
#highlighter: rouge

kramdown:
  input: GFM
  hard_wrap:  true
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
      coderay_wrap:              div
      coderay_line_numbers:      inline
      coderay_line_number_start: 1
      coderay_tab_width:         4
      coderay_bold_every:        10
      coderay_css:               style

permalink: /:year/:month/:day/:title

url: http://iyiguo.net

#分析
analytics:
  provider: google,baidu
  google:
    tracking_id: 'UA-40641589-1'

#评论
comments:
  provider: disqus
  disqus:
    short_name: oxcow

gems:
- jekyll-mentions
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-paginate